GET http://localhost:3000/

### 
GET http://localhost:3000/tweet

###
GET http://localhost:3000/user

###
GET http://localhost:3000/user/2

###
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@doe.com",
    "username": "johndoe"
}

###
PUT http://localhost:3000/user/5
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@doe.com",
    "username": "johndoe (updated)"
}

###
DELETE http://localhost:3000/user/2


### tweet
### create
POST http://localhost:3000/tweet
Content-Type: application/json

{
    "content": "Hello World again",
    "userId": 1
}

### list all
GET http://localhost:3000/tweet

### list by id
GET http://localhost:3000/tweet/10

### update
PUT http://localhost:3000/tweet/2
Content-Type: application/json

{
    "content": "Hello World again (updated)",
    "userId": 1
}

### delete
DELETE http://localhost:3000/tweet/2